name: 'Setup Python Environment'
description: 'Setup Python and install dependencies if needed'
inputs:
  python-version:
    description: 'Version of Python to setup'
    default: '3.8'
  requirements-file:
    description: 'Path to requirements file'
    required: true
  setup:
    description: 'Should we setup dependencies if cache misses'
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2.3.2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get pip cache dir
      shell: bash
      id: pip-cache
      run: |
        PIP_CACHE_DIR="$(pip cache dir)"
        echo "pip-cache=$PIP_CACHE_DIR"
        echo "pip-cache=$PIP_CACHE_DIR" >> $GITHUB_OUTPUT
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.pip-cache }}
        key: ${{ runner.os }}-pip-${{ hashFiles(inputs.requirements-file) }}
    - name: Fail if cache-hit != 'true' and setup = 'false'
      shell: bash
      if: steps.cache-dependencies.outputs.cache-hit != 'true' && inputs.setup == 'false'
      run: exit 1
    - name: Install dependencies if cache misses and setup is true
      shell: bash
      if: steps.cache-dependencies.outputs.cache-hit != 'true' && inputs.setup == 'true'
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ${{ inputs.requirements-file }}
