name: 'Setup Python Environment'
description: 'Setup Python and install dependencies if needed'
inputs:
  python-version:
    description: 'Version of Python to setup'
    default: '3.8'
  requirements-file:
    description: 'Path to requirements file'
    required: true
  setup:
    description: 'Should we setup dependencies if cache misses'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pip-cache-dir
      id: pip-cache-dir
      shell: bash
      run: |
        PIP_CACHE_DIR="$(python -m pip cache dir)"
        echo "pip-cache-dir=${PIP_CACHE_DIR}"
        echo "pip-cache-dir=${PIP_CACHE_DIR}" >> $GITHUB_OUTPUT
    - name: Setup cache
      uses: actions/cache@v2
      id: setup-cache
      with:
        path: |
          ${{ steps.pip-cache-dir.outputs.pip-cache-dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles(inputs.requirements-file) }}
    - name: Setup Python
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
    - name: Fail if cache-hit != 'true' and setup = 'false'
      shell: bash
      if: steps.setup-cache.outputs.cache-hit != 'true' && inputs.setup == 'false'
      run: |
        echo "${{ steps.setup-cache.outputs.cache-hit }} != 'true' && ${{ inputs.setup }}== 'false'"
        exit 1
    - name: pip-opts
      id: pip-opts
      shell: bash
      run: |
        if [ "${{ inputs.setup }}" == "true" ]; then
          PIP_OPTS=""
        else
          python -m pip cache list
          PIP_OPTS="--no-index --find-links=${{ steps.pip-cache-dir.outputs.pip-cache-dir }}"
        fi
        echo "PIP_OPTS=${PIP_OPTS}" >> $GITHUB_ENV
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip $PIP_OPTS
        python -m pip install -r '${{ inputs.requirements-file }}' $PIP_OPTS