name: 'Setup Python Environment'
description: 'Setup Python and install dependencies if needed'
inputs:
  python-version:
    description: 'Version of Python to setup'
    default: '3.8'
  requirements-file:
    description: 'Path to requirements file'
    required: true
  setup:
    description: 'Should we setup dependencies if cache misses'
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: ${{ inputs.requirements-file }}
    - name: Fail if cache-hit != 'true' and setup = 'false'
      shell: bash
      if: steps.setup-python.outputs.cache-hit != 'true' && inputs.setup == 'false'
      run: exit 1
    - name: Install dependencies if cache misses and setup is true
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ${{ inputs.requirements-file }} --no-index --find-links=${{ steps.setup-python.outputs.cache-path }}
